# Generated by Django 3.2.12 on 2023-01-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pocket_chords', '0002_auto_20230110_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
