# Generated by Django 3.2.12 on 2023-01-13 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pocket_chords', '0004_sketch'),
    ]

    operations = [
        migrations.AddField(
            model_name='sketch',
            name='song',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pocket_chords.song'),
        ),
        migrations.AddField(
            model_name='sketch',
            name='text',
            field=models.TextField(default='', max_length=255),
        ),
    ]
