# Generated by Django 3.2.12 on 2023-01-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pocket_chords', '0005_auto_20230113_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sketch',
            name='text',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
