# Generated by Django 3.2.12 on 2023-01-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pocket_chords', '0007_alter_sketch_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
