# Generated by Django 3.2.12 on 2023-01-20 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pocket_chords', '0008_alter_song_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sketch',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pocket_chords.song'),
        ),
    ]
