# Generated by Django 3.2.12 on 2023-01-26 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pocket_chords', '0009_alter_sketch_song'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sketch',
            options={'ordering': ('id',)},
        ),
        migrations.AlterUniqueTogether(
            name='sketch',
            unique_together={('text', 'song')},
        ),
    ]
