# Generated by Django 3.2.12 on 2023-01-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pocket_chords', '0010_song_sketch_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='sketch',
            unique_together=set(),
        ),
    ]
