# Generated by Django 3.2.12 on 2023-01-28 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pocket_chords', '0011_auto_20230128_1848'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sketch',
            unique_together={('text', 'song')},
        ),
    ]
