# Generated by Django 3.2.12 on 2023-02-02 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pocket_chords', '0012_alter_sketch_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='sketch',
            unique_together=set(),
        ),
    ]
