# Generated by Django 3.2.12 on 2023-03-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pocket_chords', '0015_chords_musicnotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicnotes',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='musicnotes',
            unique_together={('name', 'chord')},
        ),
    ]
