# Generated by Django 3.2.12 on 2023-03-03 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pocket_chords', '0016_auto_20230303_1951'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MusicNotes',
            new_name='ChordNote',
        ),
    ]
