# Generated by Django 3.2.12 on 2023-03-04 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pocket_chords', '0017_rename_musicnotes_chordnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ChordNote',
        ),
        migrations.AddConstraint(
            model_name='musicnote',
            constraint=models.CheckConstraint(check=models.Q(('name__in', ['A', 'A#', 'B', 'C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#'])), name='check_music_note_name'),
        ),
        migrations.AddField(
            model_name='chords',
            name='root_note',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pocket_chords.musicnote'),
        ),
    ]
