# Generated by Django 3.2.12 on 2023-03-04 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pocket_chords', '0018_auto_20230304_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chords',
            name='root_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pocket_chords.musicnote'),
        ),
    ]
