name: Django CI

on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: run Django unit-tests
      run: |
        pip3 install --user django
        pip3 install decouple
        python3 manage.py test
