name: Django CI

on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: run Django unit-tests
      run: |
        pip3 install --user django
        pip3 install --user python-decouple
        pip install --user psycopg2-binary
        python3 manage.py test
      env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          SQL_ENGINE: ${{ secrets.SQL_ENGINE }}
          SQL_HOST: ${{ secrets.SQL_HOST }}
          SQL_NAME: ${{ secrets.SQL_NAME }}
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
          SQL_PORT: "${{ secrets.SQL_PORT }}"
          SQL_USER: ${{ secrets.SQL_USER }} 
          
          DEBUG: ${{ secrets.SQL_DEBUG }}